backend:
  name: github
  repo: arponitis/decap_integration
  branch: main
  auth_endpoint: auth
  site_domain: arponitis.github.io/decap_integration

media_folder: static/img
public_folder: /img

collections:
  - name: docs
    label: Documentation
    folder: docs
    create: true
    fields:
      - { name: title, label: Title }
      - { name: sidebar_position, label: Sidebar Position, widget: number }
      - { name: body, label: Body, widget: markdown }

  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown } 